Document: libexpat
Title: Debian libexpat Manual
Author: <insert document author here>
Abstract: This manual describes what libexpat is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libexpat/libexpat.sgml.gz

Format: postscript
Files: /usr/share/doc/libexpat/libexpat.ps.gz

Format: text
Files: /usr/share/doc/libexpat/libexpat.text.gz

Format: HTML
Index: /usr/share/doc/libexpat/html/index.html
Files: /usr/share/doc/libexpat/html/*.html
